parameters:
#    mistra_tuto.example.class: Mistra\TutoBundle\Example

services:
#    mistra_tuto.example:
#        class: %mistra_tuto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
