<?php

namespace Mistra\TutoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DefaultController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Mistra\TutoBundle\Controller\DefaultController();
        return $instance;
    }
}
